### ISSUE TITLE
Logging stuck at gen:do_call/4 + 416 [JIRA: RIAK-2310]

### ISSUE THREAD

**Issue by jbaramidze** [basho/lager#301]
Hello
process is stuck with suck backtrace:
    <<"Program counter: 0x00007fa69006ea20 (gen:do_call/4 + 416)
    CP: 0x0000000000000000 (invalid)
    arity = 0

   0x00007fa684294520 Return addr 0x00007fa6900615e8 (gen_event:rpc/2 + 96)
    y(0)     #Ref<0.0.262146.9037>
    y(1)     infinity
    y(2)     {sync_notify,{log,{lager_msg,[],[{application,myapp},{module,mymodule},    {function,do_route},{line,322},{pid,\"<0.32435.0>\"},{node,'myapp@machine007'}],debug,{[\"201\">>}]},}]}\"]}}}
    y(3)     <0.32435.0>
    y(4)     <0.56.0>
    y(5)     []

Return addr 0x00007fa6887c64e0 (lager:do_log_impl/10 + 968)

just called lager:debug/3, tried attaching remote terminal and ran
 lager:status()
but it gets stuck, messages get accumulated on that thread, I got 
 {message_queue_len,948},
already.

thanks.

**Comment by mrallen1** [comment]
Thanks for the report. Would you please specify which release of lager you're using? 2.1.x, 3.x?

**Comment by slfritchie** [comment]
Two bits of additional info would be helpful.

1. What version of Erlang/OTP?
2. What is pid 0.56.0?

Some versions of Erlang/OTP have a bug in console I/O handling, and if the bug is in pid 0.56.0 getting stuck, then there's only so much that lager can do about it.

**Comment by jbaramidze** [comment]
Thanks for response.

I'm using Erlang/OTP 18

backtrace from 0.56.0:

{backtrace,<<"Program counter: 0x00007fa687e3c978 (io:execute_request/2 + 328)
CP: 0x0000000000000000 (invalid)
arity = 0

0x00007fa6857ffa60 Return addr 0x00007fa687e3a560 (io:o_request/3 + 96)
y(0)     #Ref<0.0.262146.9035>
y(1)     <0.31.0>
y(2)     false

0x00007fa6857ffa80 Return addr 0x00007fa6887d3310 (lager_console_backend:handle_event/2 + 600)

and from 0.31.0:

{backtrace,<<"Program counter: 0x00007fa68f14e348 (unknown function)
CP: 0x00007fa68871dae8 (user:put_chars/3 + 160)
arity = 2
   #Port<0.474>
   {<0.31.0>,{command,<<"semecommand">>}}

0x00007fa68432bbd8 Return addr 0x00007fa68871c880 (user:do_io_request/5 + 88)
y(0)     {[],[]}

0x00007fa68432bbe8 Return addr 0x00007fa68871c538 (user:server_loop/2 + 1464)

**Comment by jbaramidze** [comment]
@mrallen1 
sorry didn't notice your question, I'm using 3.0.1

**Comment by slfritchie** [comment]
@jbaramidze That looks suspiciously like an I/O server bug that Basho once ran into, IIRC, on Solaris but a few major versions of the VM ago.  When Riak uses the remote console ("riak attach"), a sysadmin typing stuff at the console could put the I/O server into a state where the error_logger (or lager) would never send whatever reply that error_logger was expecting.

One workaround for the bug was to disable error logging to the console altogether.  Also, doing something like "riak attach" followed by pressing Return on the console would wake up the I/O server, send the whatever reply, and then error_logger could wake up and finish draining its queue.  We/Basho had thought that that bug had been fixed in the VM's console I/O server, but ... perhaps not?

**Comment by jonmeredith** [comment]
I think it would need attach-direct to use the pipes rather than over
disterl.

**Comment by slfritchie** [comment]
Agreed, though back at that time (exact details are hazy) "riak attach" was the pipe-based method that newer Riak changed to "riak attach-direct". Or starting the VM with the CLI shell, like "riak console" does.

**Comment by mrallen1** [comment]
@jbaramidze Did you ever find out more information about this failure?  Just wondering if Scott and Jon's conclusion are on the right track.

**Comment by mrallen1** [comment]
I am going to close this issue because it's been 8 weeks since the last update. Please reopen if needed. Thanks.
